In [1]:
import tensorflow as tf
import numpy as np

# Tensorflow 자료형 
# 1. 상수형(constant) 
# 2. placeholder  
# 3. variable(변수형)

# 상수형(constant) : 
# 상수를 저장하는 데이터 형식 

# tf.constant(value, dtype=None, shape=None, name='Const')

In [ ]:
#value: 상수의 값
#dtype: 상수의 데이터형
#shape: 행렬의 차원
#name: 상수의 이름을 정의 

In [22]:
a = tf.constant([5], dtype=float)
print(a)

Tensor("Const_2:0", shape=(1,), dtype=float32)


In [23]:
sess = tf.Session()
sess.run(a)

array([5.], dtype=float32)

# Matmul : 
# 행렬 간 곱셈을 위해서는 '*'가 아닌 matmul함수를 이용하여 곱셈을 해야 합니다.

In [9]:
matrix1 = tf.constant([[1,2],[3,4]])  #shape(2,2)
matrix2 = tf.constant([[1],[3]])      #shape(2,1)

In [10]:
tf.(matrix1, matrix2).(session=tf.Session())

SyntaxError: invalid syntax (<ipython-input-10-edfd1146ff8f>, line 1)

# reduce_mean : 
# 행렬에서 여러 값이 있을 때 줄여주는 역할, axis(=축)에 따라서 평균을 내어줌 

In [7]:
x = [[1.,2.],
      [3.,4.]]

In [9]:
a = tf.reduce_mean(x).eval(session = tf.Session())
print(a)

2.5


In [12]:
#axis=0으로 reduce mean
b = tf.reduce_mean(x,axis=0).eval(session = tf.Session())
print(b)

[2. 3.]


In [13]:
#axis=1으로 reduce mean
c = tf.reduce_mean(x,axis=1).eval(session = tf.Session())
print(c)

[1.5 3.5]


# reduce_sum 

In [14]:
x = [[1,1,1],
     [1,1,1]]

In [24]:
#reduces all dimensions 전체합을 구한다.
#즉, [1+1+1+1+1+1=6]
#모든 차원이 제거되고 단 하나의 스칼라 값이 출력된다.
tf.reduce_sum(x).eval(session=sess)

6

In [56]:
#keepdims=True : 최초 차원수와 동일하게 차원 수를 유지한다.
tf.reduce_sum(x, ,).eval(session=sess)

array([[2, 2, 2]])

In [57]:
tf.reduce_sum(x, ,).eval(session=sess)

array([[3],
       [3]])

In [58]:
tf.reduce_sum(x, axis=1).eval(session=sess)

array([3, 3])

# Reshape : 
# tensor의 shape을 변경할 때 사용, 안에 shape에 원하는 값을 넣으면 해당 shape 맞게 조정된다.

In [25]:
sess = tf.Session()

In [26]:
x = [i for i in range(10)] #0부터 9까지 배열을 만든다.
print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [36]:
#마지막 차원에 2개의 값으로 고정된 2차원 행렬을 만든다.
y =tf.reshape(x, shape=[-1,2]).eval(session=sess)
print(y)
print("y.shape:", y.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
y.shape: (5, 2)


In [37]:
t = np.array(
    [[
        [0,1,2],
        [3,4,5]
    ],
        
        [
            [6,7,8],
            [9,10,11]
        ]
    ]
)

In [38]:
print(t.shape)

(2, 2, 3)


In [44]:
#1차원 행렬을 만든다.
z =tf.reshape(x, shape=[-1]).eval(session=sess)
print(z)
print("z.shape:", z.shape)

[0 1 2 3 4 5 6 7 8 9]
z.shape: (10,)


In [49]:
#특히 shape에 -1를 입력하면 고정된 차원은 우선 채우고 남은 부분을 알아서 채워준다.
#마지막 차원에 3개의 값으로 고정된 2차원 행렬을 만든다. 
z1 = tf.reshape(t, shape = [-1,3]).eval(session=sess)
print(z1)
print("z1.shape:", z1.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
z1.shape: (4, 3)


In [45]:
#마지막 차원에 3개, 이전차원 1개 값으로 고정된 3차원 행렬을 만든다. 
z2 = tf.reshape(t, shape = [-1,1,3]).eval(session=sess)
print(z2)
print("z2.shape:", z2.shape)

[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]]
z2.shape: (4, 1, 3)


# squeeze 함수 :
# tensor에서 크기가 1인 차원을 삭제합니다.

In [50]:
x = np.array(
[
    [0],[1],[2]
]
)
print("x.shape:", x.shape)

x.shape: (3, 1)


In [51]:
#차원 중 사이즈 1인 것을 찾아 짜서 제거한다.
y = tf.squeeze(x).eval(session=sess)
print(y)
print("y.shape:", y.shape)

[0 1 2]
y.shape: (3,)


# One hot Encoding : 
# 데이터를 0과 1의 나열로 바꿔주는 것

In [52]:
tf.one_hot([[0],[1],[2]], depth=4).eval(session=sess)

array([[[1., 0., 0., 0.]],

       [[0., 1., 0., 0.]],

       [[0., 0., 1., 0.]]], dtype=float32)

# Casting : 
# dtype으로 바꿔준다. 주로 True, False를 0과 1로 바꿔준다.

In [58]:
print(tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval(session=tf.Session()))

[1 2 3 4]


In [59]:
print(tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval(session=tf.Session()))

[1 0 1 0]


# stack 함수 : 
# stack 구조로 쌓아주는 의미 

In [60]:
x1 = [1,2]
x2 = [3,4]
x3 = [5,6]

In [66]:
y = tf.stack([x1,x2,x3],axis=0).eval(session=sess)
print(y)
print("y.shape:", y.shape) #shape 함수: 배열의 크기 반환 

[[1 2]
 [3 4]
 [5 6]]
y.shape: (3, 2)


# Ones and Zeros like : 
# 주어진 shape에 0 또는 1로 채운 행렬을 만들어줌 

In [67]:
x = [[0, 1, 2],
     [2, 1, 0]]

In [70]:
print(tf.ones_like(x).eval(session=tf.Session())) # 1로 채운

[[1 1 1]
 [1 1 1]]


In [71]:
print(tf.zeros_like(x).eval(session=tf.Session())) # 0으로 채운

[[0 0 0]
 [0 0 0]]


# argmax, argmin 함수
# - softmax를 통해 나온 결과중 최대값의 인덱스를 얻고자 할 때 사용한다. 

In [72]:
x = [0,0,0,0,1]
tf.argmax(x).eval(session=sess)

4

In [74]:
#참고로 최대 값이 2개 이상인 경우 더 앞선 인덱스 값이 나옴 
x = [5, 5, 4]
tf.argmax(x).eval(session=sess)

0

In [75]:
x = [0, 4, 1, 2]
tf.argmin(x).eval(session=sess)

0

In [76]:
x = [[2,4,6],
      [9,3,1]]

In [81]:
#max인덱스(2,9), max인덱스(4,3), max인덱스(6,1) -> [1,0,0] axis=0 -> 행 인데 파이썬에서 배열이 [1][1]의 경우 한 컬럼에 대한 것이므로 행이 아니라 열이다. 때문에 결과가 1.0.0이 나온다.
tf.argmax(x,axis=0).eval(session=sess)

array([1, 0, 0], dtype=int64)

In [82]:
#max인덱스(2,3,4), max인덱스(9,3,1) -> [2,0]
tf.argmax(x,axis=1 ).eval(session=sess)

array([2, 0], dtype=int64)